### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jirkasemmler** [nikihlawiczka/PROJEKT-Vizitka#1]
- [x] https://prnt.sc/9X4CnGyIjU8v chybi stin a text ma byt zarovnan do bloku
- [x] https://github.com/nikihlawiczka/PROJEKT-Vizitka/blob/main/style.css#L47 jak rikal Ludek na lekci - nestylujeme obecne prvky jako A nebo IMG
- [x] https://github.com/nikihlawiczka/PROJEKT-Vizitka/blob/main/style.css#L72 toto je asi snaha o vizualni zanoreni. Takto to prosim nedelej. Casem si ukazeme nastroje jak to delat

**Comment by nikihlawiczka** [comment]
Ahojky, děkuji za připomínky. Vše opraveno. Obrázek stín měl, ale je pravda, že nešel moc vidět, zvýraznila jsem ho. A to "zanoření" jsem vlastně neměla ani v úmyslu, já si to odsadila pro sebe, abych to nezapomněla :D. Každopádně už to dělat nebudu. Ještě jednou díky.
